---
title: "Two-Pop Persistence"
author: "Stuart E. Jones and Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

Model looking at factors that affect bacterial persistence

```{r}
getwd()
setwd("~/GitHub/Dimensions/Aim1/PersistenceModel")
```

Install packages
```{r}
require("deSolve")
```

# Model 1: First-order decay
```{r}
# Function for persistence
persist <- function(t, x, parms){
  with(as.list(c(parms, x)),{
		dBadt = -Ba*da		#g (L*day)^-1
		
		res=c(dBadt)
		list(res)
	})
}

# Parameters
parms = c(da = 0.1)
times = seq(0, 1000, 0.1)
init = c(Ba = 0.00002)

# Output
outP <- ode(y = init, times = times, func = persist, parms = parms)
outP <- data.frame(outP, log10(outP[,2]/(20e-15)))
colnames(outP)[3] <- "logcells.ml"
outP <- subset(outP, outP[,3] >= 0)
```

# Model 2: Cannibalism
```{r}
# Function for cannibalsims where dead bacteria are consumed by live bacteria
persistCannibalism <- function(t, x, parms){
  with(as.list(c(parms, x)),{
		dBadt = Ba*(C*Va)/(C+Ka)*Ea-Ba*da		#g (L*day)^-1
		dCdt = Ba*da*m-Ba*(C*Va)/(C+Ka)		#g (L*day)^-1
		
		res=c(dBadt,dCdt)
		list(res)
	})
}

# Parameters
parms = c(Va = 12, Ka = 0.0011, Ea = 0.5, da = 0.1, m = 0.5)
times = seq(0, 1000, 0.1)
init = c(Ba = 0.00002, C = 0)

# Output
outPC = ode(y = init, times = times, func = persistCannibalism, parms = parms)
outPC <- data.frame(outPC, log10(outPC[,2]/(20e-15)))
colnames(outPC)[4] <- "logcells.ml"
outPC <- subset(outPC, outPC[,4] >= 0)
```

# Model 3: Adaptation
```{r}
# Function for two-species model with mutant and ancestros with different traits
persistCannibalismMut <- function(t, x, parms){
  with(as.list(c(parms, x)),{
		dBadt = Ba*(C*Va)/(C+Ka)*Ea-Ba*da
		dBmdt = Bm*(C*Vm)/(C+Km)*Em-Bm*dm
		dCdt = Ba*da*m-Ba*(C*Va)/(C+Ka)+Bm*dm*m-Bm*(C*Vm)/(C+Km)
		
		res=c(dBadt, dBmdt, dCdt)
		list(res)
	})
}

# Parameters
fracMut <- 1e-5 # fraction of initial population that are mutant
parmsMut <- c(Va = 12, Ka = 0.0011, Ea = 0.5, da = 0.1, Vm = 12, Km = 0.0011, 
             Em = 0.75, dm = 0.05, m = 0.5)
initMut <- c(Ba = 0.00002-(0.00002*fracMut), Bm = 0.00002*fracMut, C = 0)

# Output
outPCmut <- ode(y = initMut, times = times, func = persistCannibalismMut, 
            parms = parmsMut)
outPCmut <- data.frame(outPCmut, log10(outPCmut[,2]/(20e-15)), log10(outPCmut[,3]/(20e-15)))
outPCmut <- data.frame(outPCmut, log10((outPCmut[,2] + outPCmut[,3])/(20e-15)))
outPCmut <- subset(outPCmut, outPCmut[,7] >= 0)
colnames(outPCmut)[5:7] <- c("a.logcells.ml", "m.logcells.ml", "t.logcells.ml")
```

Plotting
```{r}
png(filename="~/GitHub/Dimensions/Aim1/PersistenceModel/figures/decay.png",
    width = 1200, height = 700, res = 96*2)

# par(mfrow = c(1, 1), mar=c(2, 4, 2, 2) + 0.1)

par(mar = c(5, 7, 5, 7))
decay.plot <- plot(outP[,1], outP[,3], type = "l", lty = 1, col = "dark green", yaxt = "n", xaxt = "n", lwd = 3,
        cex.lab = 1.5, cex.axis = 1.5, xlab = "Time (days)", ylab = NA,
        xlim = c(-25, 525))
box(lwd = 3)

mtext(expression('Bacteria ml'^-1), side = 2, outer = TRUE, cex = 1.5, line = -3, adj = 0.5)


# Add ticks and tick labels

axis(side = 2, lwd.ticks = 3, cex.axis = 1.5, las = 1,
     labels = expression(10^1, 10^3, 10^5, 10^7, 10^9),
     at = c(1, 3, 5, 7, 9))
 
axis(side = 4, lwd.ticks = 3, cex.axis = 1.5, las = 1,
    at=c(1, 3, 5, 7, 9), labels = F)
 
axis(side = 1, lwd.ticks = 3, cex.axis = 1.5, las = 1,
    labels = c(0, 250, 500), at = c(0, 250, 500))

axis(side = 3, lwd.ticks = 3, cex.axis = 1.5, las = 1,
    at = c(0, 250, 500), labels = F)

# Add cannibalism
points(outPC[,1], outPC[,4], type = "l", col = "blue", lty = 1, lwd = 3)

# Add adaptation
points(outPCmut[,1], outPCmut[,7], type = "l", col = "red", lty = 1, lwd = 3)

dev.off()
graphics.off()
```