---
title: "Curve Fitting Death"
author: "Stuart E. Jones and Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

```{r}
rm(list = ls())
getwd()
setwd("~/GitHub/Dimensions/Aim1/DeathCurves/")
```

```{r}
## Load Data
obs <- read.csv("data/longtermdormancy_20150526b.csv", header = TRUE, stringsAsFactors = FALSE)
obs <- obs[!(obs$Notes == "contaminated"),]
obs$Abund <- as.numeric(obs$Colonies) * 10 ^ as.numeric(obs$Dilution) + 1
strains <- sort(unique(obs$Strain))
strains <- strains[table(obs$Strain)>10]
obs <- obs[obs$Strain%in%strains,]
time <- (as.numeric(strptime(obs$Firstread_date,format="%d-%b-%y",tz = "EST")) - 
        as.numeric(strptime(obs$Dormstart_date,format="%d-%b-%y",tz="EST")))/(3600*24)
obs <- data.frame(obs, time)
```

```{r}
KBS0703 <- obs[(obs$Strain == "KBS0703"),] # Arthrobacter
KBS0714 <- obs[(obs$Strain == "KBS0714"),] # Micrococcus
KBS0710 <- obs[(obs$Strain == "KBS0710"),] # Pseudomonas
KBS0706 <- obs[(obs$Strain == "KBS0706"),] # Pseudomonas

png(filename="~/GitHub/Dimensions/Aim1/DeathCurves/figures/curve.fitting.png",
    width = 2400, height = 2400, res = 96*2)

# par(mfrow=c(2,2))
# par(mar = c(5, 7, 5, 7))
# par(oma = c(5,4,0,0))

par(mfrow = c(2,2),
          oma = c(5,4,0,0) + 0.5,
          mar = c(0,0,1,1) + 0.5)

# KBS0703
plot(KBS0703$time, KBS0703$Abund, pch = 22, 
          bg = "white", col = "black", lwd = 6, cex = 6, log = "y", xlab = NA, ylab = NA,
          xlim = c(0, 900), ylim = c(10, 1000000000), yaxt = "n", xaxt = "n")
box(lwd = 6)

axis(side = 2, lwd.ticks = 6, cex.axis = 3, las = 1,
     labels = expression(10^1, 10^3, 10^5, 10^7, 10^9),
     at = c(10^1, 10^3, 10^5, 10^7, 10^9))
 
axis(side = 4, lwd.ticks = 6, cex.axis = 3, las = 1,
    at=c(10^1, 10^3, 10^5, 10^7, 10^9), labels = F)
 
axis(side = 1, lwd.ticks = 6, cex.axis = 3, las = 1,
    at = c(0, 300, 600, 900), labels = F)

axis(side = 3, lwd.ticks = 6, cex.axis = 3, las = 1,
    at = c(0, 300, 600, 900), labels = F)

# KBS0714
plot(KBS0714$time, KBS0714$Abund, pch = 22, 
          bg = "white", col = "black", lwd = 6, cex = 6, log = "y", xlab = NA, ylab = NA,
          xlim = c(0, 900), ylim = c(10, 1000000000), yaxt = "n", xaxt = "n")
box(lwd = 6)

axis(side = 2, lwd.ticks = 6, cex.axis = 3, las = 1,
     at=c(10^1, 10^3, 10^5, 10^7, 10^9), labels = F)
 
axis(side = 4, lwd.ticks = 6, cex.axis = 3, las = 1,
    at=c(10^1, 10^3, 10^5, 10^7, 10^9), labels = F)
 
axis(side = 1, lwd.ticks = 6, cex.axis = 3, las = 1,
    at = c(0, 300, 600, 900), labels = F)

axis(side = 3, lwd.ticks = 6, cex.axis = 3, las = 1,
    at = c(0, 300, 600, 900), labels = F)

# KBS0710
plot(KBS0710$time, KBS0710$Abund, pch = 22, 
          bg = "white", col = "black", lwd = 6, cex = 6, log = "y", xlab = NA, ylab = NA,
          xlim = c(0, 900), ylim = c(10, 1000000000), yaxt = "n", xaxt = "n")
box(lwd = 6)

axis(side = 2, lwd.ticks = 6, cex.axis = 3, las = 1,
     labels = expression(10^1, 10^3, 10^5, 10^7, 10^9),
     at = c(10^1, 10^3, 10^5, 10^7, 10^9))
 
axis(side = 4, lwd.ticks = 6, cex.axis = 3, las = 1,
    at=c(10^1, 10^3, 10^5, 10^7, 10^9), labels = F)
 
axis(side = 1, lwd.ticks = 6, cex.axis = 3, las = 1, mgp = c(3, 3, 0),
    labels = c(0, 300, 600, 900), at = c(0, 300, 600, 900))

axis(side = 3, lwd.ticks = 6, cex.axis = 3, las = 1,
    at = c(0, 300, 600, 900), labels = F)

# KBS0706
plot(KBS0706$time, KBS0706$Abund, pch = 22, 
          bg = "white", col = "black", lwd = 6, cex = 6, log = "y", xlab = NA, ylab = NA,
          xlim = c(0, 900), ylim = c(10, 1000000000), yaxt = "n", xaxt = "n")
box(lwd = 6)

axis(side = 2, lwd.ticks = 6, cex.axis = 3, las = 1,
 at=c(10^1, 10^3, 10^5, 10^7, 10^9), labels = F)
 
axis(side = 4, lwd.ticks = 6, cex.axis = 3, las = 1,
    at=c(10^1, 10^3, 10^5, 10^7, 10^9), labels = F)
 
axis(side = 1, lwd.ticks = 6, cex.axis = 3, las = 1, mgp = c(3, 3, 0),
    labels = c(0, 300, 600, 900), at = c(0, 300, 600, 900))

axis(side = 3, lwd.ticks = 6, cex.axis = 3, las = 1,
    at = c(0, 300, 600, 900), labels = F)

dev.off()
graphics.off()
```

# Test of purple vs. white Janthinobacterium
```{r}
KBS0711 <- obs[(obs$Strain == "KBS0711"),] # purple
KBS0711W <- obs[(obs$Strain == "KBS0711W"),] # white

plot.new()
png(filename="~/GitHub/Dimensions/Aim1/DeathCurves/figures/Janthino.curve.fitting.png",
    width = 2400, height = 2400, res = 96*2)

par(mar = c(5, 7, 5, 7))

plot(KBS0711$time, KBS0711$Abund, pch = 22, 
          bg = "purple", col = "black", lwd = 6, cex = 6, log = "y", xlab = NA, ylab = NA,
          xlim = c(0, 900), ylim = c(10, 1000000000), yaxt = "n", xaxt = "n")
box(lwd = 6)

axis(side = 2, lwd.ticks = 6, cex.axis = 3, las = 1,
     labels = expression(10^1, 10^3, 10^5, 10^7, 10^9),
     at = c(10^1, 10^3, 10^5, 10^7, 10^9))
 
axis(side = 4, lwd.ticks = 6, cex.axis = 3, las = 1,
    at=c(10^1, 10^3, 10^5, 10^7, 10^9), labels = F)
 
axis(side = 1, lwd.ticks = 6, cex.axis = 3, las = 1, mgp = c(3, 3, 0),
    labels = c(0, 300, 600, 900), at = c(0, 300, 600, 900))

axis(side = 3, lwd.ticks = 6, cex.axis = 3, las = 1,
    at = c(0, 300, 600, 900), labels = F)

points(KBS0711W$time, KBS0711W$Abund, pch = 22, 
          bg = "white", col = "black", lwd = 6, cex = 6, xlab = NA, ylab = NA,
          xlim = c(0, 900), ylim = c(10, 1000000000), yaxt = "n", xaxt = "n")
dev.off()
graphics.off()
```
