---
title: "Bacillus death rate"
author: "Jay T. Lennon"
date: "`r format(Sys.time(), '%d %B, %Y')`"
header-includes:
   - \usepackage{array}
output: pdf_document
geometry: margin=2.54cm
---

# Set working directory
```{r, results='hide', warning=FALSE, message=FALSE}
rm(list = ls())
getwd() 
setwd("~/GitHub/LTDE")
require(bbmle)
require("grid")
require("png")
```

# Load data
```{r}
obs <- read.csv("data/demography/20190417_spo0a.csv", header = TRUE, stringsAsFactors = FALSE)

# Calculate total CFUs for Spo0A line
Spo0A <- obs[ which(obs$Strain == "Spo0A"),]
Spo0A.Ab <- Spo0A$NT * 10^(Spo0A$dil.nt) * 10 + Spo0A$HT * 10^(Spo0A$dil.ht) * 10

# Calculate total CFUs for KBS0812 (wt) line
KBS0812 <- obs[ which(obs$Strain == "KBS0812"),]
KBS0812.Ab <- KBS0812$NT * 10^(KBS0812$dil.nt) * 10 + KBS0812$HT * 10^(KBS0812$dil.ht) * 10
  
time <- obs$hour/24

```

# Plot survivorship data: abundance
```{r}
png(filename="~/GitHub/LTDE/figs/Spo0A.death.png",
     width = 1200, height = 1200, res = 96*2)

par(mar = c(5, 7, 5, 7))

plot(KBS0812$hour/24, KBS0812.Ab, pch = 22, 
          bg = "white", col = "black", lwd = 2, log = "y", cex = 2, xlab = NA, ylab = NA,
          xlim = c(-2, 10), ylim = c(1000000, 1000000000), yaxt = "n", xaxt = "n")


points(Spo0A$hour/24, Spo0A.Ab, pch = 22, 
          bg = "red", col = "black", lwd = 2, cex = 2)
box(lwd = 2)

axis(side = 2, lwd.ticks = 2, cex.axis = 1.25, las = 1,
     labels = expression(10^6, 10^7, 10^8, 10^9),
     at = c(10^6, 10^7, 10^8, 10^9))

axis(side = 4, lwd.ticks = 2, cex.axis = 1.25,
    at=c(10^6, 10^7, 10^8, 10^9), labels = F)

axis(side = 1, lwd.ticks = 2, cex.axis = 1.25,
    at = c(0, 2, 4, 6, 8), labels = T)

axis(side = 3, lwd.ticks = 2, cex.axis = 1.25,
    at = c(0, 2, 4, 6, 8), labels = F)

mtext('Time (d)', side = 1, outer = TRUE, cex = 2, 
      line = -2, adj = 0.5)

mtext(expression('Bacteria (CFU ml'^-1*')'), side = 2, outer = TRUE, cex = 2, 
      line = -3.5, adj = 0.5)

dev.off()
graphics.off()

# Show Plot
img <- readPNG("~/GitHub/SporMut/output/survivorship.png")
grid.raster(img)
```

# Statistics
```{r}
rep1 <- subset(KBS0812, Rep == 1)
rep2 <- subset(KBS0812, Rep == 2)
rep3 <- subset(KBS0812, Rep == 3)
rep4 <- subset(KBS0812, Rep == 4)

fit1 <- lm (Abund ~ time, data = rep1)
summary(fit1)
slp1 <- coef(fit1)[2]
int1 <- coef(fit1)[1]

fit2 <- lm (Abund ~ time, data = rep2)
summary(fit2)
slp2 <- coef(fit2)[2]
int2 <- coef(fit2)[1]

fit3 <- lm (Abund ~ time, data = rep3)
summary(fit3)
slp3 <- coef(fit3)[2]
int3 <- coef(fit3)[1]

fit4 <- lm (Abund ~ time, data = rep4)
summary(fit4)
slp4 <- coef(fit4)[2]
int4 <- coef(fit4)[1]

slopes <- data.frame(slp1, slp2, slp3, slp4)
slope.test <- t.test(slopes, mu = 0)
sem <- function(x, ...){sd(x, na.rm = TRUE)/sqrt(length(na.omit(x)))}
mean.slp <- mean(slp1, slp2, slp3, slp4)
sem(slopes)

intercepts <- data.frame(int1, int2, int3, int4)
mean.int <- mean(int1, int2, int3, int4)
# mortality = 16.1 +/- 4.89 cells per day
# x-intercept 16.1 x = 112257.8 (0) = 

# How long would it take Bacillus to starve to death?
abs(mean.int/mean.slp)/365
# About 19 years
```

```{r}

obs <- read.csv("data/longtermdormancy_20151112_nocomments.csv", 
                header = TRUE, stringsAsFactors = FALSE)

obs <- obs[which (obs$Strain == "KBS0812"), ]

## Adding 1 to deal with log(0) observations
obs$Abund <- as.numeric(obs$Colonies) * 10 ^ as.numeric(obs$Dilution) + 1
strains <- sort(unique(obs$Strain))
strains <- strains[table(obs$Strain)>10]
obs <- obs[obs$Strain%in%strains,]

# Create matrix to population with output
summ <- matrix(NA,length(strains)*max(obs$Rep),12)
```

## 2) RUN WEIBULL MODEL
```{r}
pdf('~/GitHub/SporMut/output/Weibull.fits.pdf') # Uncomment to create pdf that will plot data and fits
counter <- 1

for(i in 1:length(strains)){
  strainObs=obs[obs$Strain==strains[i],]
  
  reps=unique(strainObs$Rep)
  for(j in 1:length(reps)){
    
    repObs=strainObs[strainObs$Rep==reps[j],]
    # minimum of 10 data points
    if(nrow(repObs)>10){
      start=repObs[1,1]
      time=(as.numeric(strptime(repObs$Firstread_date,format="%d-%b-%y",tz="EST"))-
              as.numeric(strptime(start,format="%d-%b-%y",tz="EST")))/(3600*24)
      repObs["time"] <- time + 1
      repObs["logabund"] <- log10(repObs$Abund)
      if (repObs["logabund"][[1]][2] - repObs["logabund"][[1]][1] > 1){
        repObs <- repObs[-c(1), ]
      }
      #repObs["prop"] <- repObs$logabund / repObs$logabund[1]
      repObs["prop"] <- repObs$Abund / repObs$Abund[1]
      # Initial parameters
      #A = 200 # Initial death (larger = slower) 
      #B = 1 # Bend (upper = 1 = first-order decay)
      #C = round(max(repObs$logabund),1) # intercept
      #Z = 6 # Error
      grids<-list(a=c(1,10,50,100,200),b=c(0.1,0.5,1,1.1,1.5),z=c(0.1,1,10))
      #start<-list(a=NA,b=NA,c=round(max(repObs$logabund),1),z=NA)
      start<-list(a=NA,b=NA,z=NA)
      grid.starts<-as.matrix(expand.grid(grids))
      ncombos<-dim(grid.starts)[[1]]
      # cycle through each combo
      res.mat<-matrix(NA,nrow=ncombos,ncol=I(length(start)+1))
      res.mod<-list()
      for(k in 1:dim(grid.starts)[[1]]){
        #some how need to match grid parameters to start lists.
        mod.start<-as.list(grid.starts[k,])	
        new.start<-start
        new.start[names(start) %in% names(mod.start)]<-mod.start
        pscale<-as.numeric(new.start)
        names(pscale)<-names(new.start)
        fit <- mle2(minuslogl=prop ~ dnorm(mean = exp( -1 * ((time / a)^ b)), sd = z), 
                                start = new.start, data = repObs, 
                                control=list(parscale=pscale, maxit=1000), 
                                 method="Nelder-Mead", hessian = T)
        #fit <- mle2(minuslogl=prop ~ dnorm(mean =  -1 * ((time / a)^ b), sd = z), 
        #                        start = new.start, data = repObs, 
        #                        control=list(parscale=pscale, maxit=1000), 
        #                         method="Nelder-Mead", hessian = T)
        res.mat[k,]<-c(coef(fit),AIC(fit))		
        res.mod[[k]]<-fit
      }
      colnames(res.mat)<-c(names(coef(fit)),"AIC")
      best.fit<-res.mod[[which(res.mat[,'AIC']==min(res.mat[,'AIC']))[1]]]
      summ[counter,1]=strains[i]
      summ[counter,2]=reps[j]
      #CIs <- confint( profile(best.fit))
      print(coef(best.fit))
      # a
      summ[counter,3]=coef(best.fit)[1]
      # b
      summ[counter,4]=coef(best.fit)[2]
      # c
      summ[counter,5]=coef(best.fit)[3]
      #summ[counter,5]= round(max(repObs$logabund),1)
      # z
      summ[counter,6]=AIC(best.fit)
      #summ[counter,8]=CIs[1,1]
      #summ[counter,9]=CIs[1,2]
      #summ[counter,10]=CIs[2,1]
      #summ[counter,11]=CIs[2,2]
      #summ[counter,12]=CIs[3,1]
      #summ[counter,13]=CIs[3,2]
      #summ[counter,14]=CIs[4,1]
      #summ[counter,15]=CIs[4,2]
      summ[counter,7]=length(repObs$time)
      

      ### *** Comment/Uncomment following code to make pdf figs*** ###
      title=paste(strains[i],"  rep ",reps[j])
      plot(repObs$time,repObs$prop,main=title,ylim=c(0,1))
      predTime=seq(0,max(repObs$time))
      print(strains[i])
      print(reps[j])
      #exp( -1 * ((time / a)^ b))
      #coef(best.fit)[3] 
      lines(repObs$time, exp( -1 * ((repObs$time / coef(best.fit)[1] )^ coef(best.fit)[2])), 
              lwd=4, lty=2, col = "red")
      #lines(repObs$time, (-1 * ((repObs$time / coef(best.fit)[1] )^ coef(best.fit)[2])), 
      #        lwd=4, lty=2, col = "red")
      counter=counter+1
    }
  }
}
  
dev.off() 
summ=summ[!is.na(summ[,1]),]
#colnames(summ)=c('strain','rep','a','b','c','z','AIC', 'a.CI.2.5', 'a.CI.97.5', 'b.CI.2.5', 'b.CI.97.5', 'c.CI.2.5', 'c.CI.97.5', 'z.CI.2.5', 'z.CI.97.5')
colnames(summ)=c('strain','rep','a','b','z','AIC', 'N.obs')

write.csv(summ,"output/weibull_results.csv")
```
