IMPORTANT WARNING: Alignment column 42 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 44 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 47 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 95 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 96 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 97 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 106 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 142 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 145 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 163 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 167 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 168 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 309 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 310 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 314 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 571 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 581 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 607 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 608 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 609 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 610 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 622 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 623 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 970 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 977 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1130 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1131 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1138 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1144 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1145 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1169 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1192 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1251 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1252 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1301 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1675 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1676 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1677 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1678 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1679 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1680 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1681 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1682 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1683 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1684 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1685 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1686 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1687 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1688 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1689 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1690 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1691 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1692 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1693 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1694 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1695 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1696 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1697 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1698 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1699 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1700 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1701 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1702 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1703 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1704 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1705 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1706 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1707 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1708 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1709 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1710 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1711 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1712 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1713 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1749 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1808 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1813 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1816 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1818 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1819 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1821 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1863 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1864 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1865 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1866 contains only undetermined values which will be treated as missing data
IMPORTANT WARNING: Alignment column 1867 contains only undetermined values which will be treated as missing data

IMPORTANT WARNING
Found 86 columns that contain only undetermined values which will be treated as missing data.
Normally these columns should be excluded from the analysis.

Just in case you might need it, an alignment file with 
undetermined columns removed is printed to file ./June2017.clustal.afa.fasta.reduced


Using BFGS method to optimize GTR rate parameters, to disable this specify "--no-bfgs" 



This is RAxML version 8.1.3 released by Alexandros Stamatakis on August 13 2014.

With greatly appreciated code contributions by:
Andre Aberer      (HITS)
Simon Berger      (HITS)
Alexey Kozlov     (HITS)
Kassian Kobert    (HITS)
David Dao         (KIT and HITS)
Nick Pattengale   (Sandia)
Wayne Pfeiffer    (SDSC)
Akifumi S. Tanabe (NRIFS)

Alignment has 1067 distinct alignment patterns

Proportion of gaps and completely undetermined characters in this alignment: 29.19%

RAxML rapid bootstrapping and subsequent ML search

Using 1 distinct models/data partitions with joint branch length optimization



Executing 1000 rapid bootstrap inferences and thereafter a thorough ML search 

All free model parameters will be estimated by RAxML
GAMMA model of rate heteorgeneity, ML estimate of alpha-parameter

GAMMA Model parameters will be estimated up to an accuracy of 0.1000000000 Log Likelihood units

Partition: 0
Alignment Patterns: 1067
Name: No Name Provided
DataType: DNA
Substitution Matrix: GTR




RAxML was called as follows:

raxmlHPC-PTHREADS -T 4 -f a -m GTRGAMMA -p 12345 -x 12345 -o Methanosarcina -# autoMRE -s ./June2017.clustal.afa.fasta -n LTDE.ML 



Time for BS model parameter optimization 0.214259
Bootstrap[0]: Time 1.231504 seconds, bootstrap likelihood -13430.672959, best rearrangement setting 13
Bootstrap[1]: Time 0.958204 seconds, bootstrap likelihood -13873.531485, best rearrangement setting 13
Bootstrap[2]: Time 1.008542 seconds, bootstrap likelihood -13632.267599, best rearrangement setting 12
Bootstrap[3]: Time 1.087793 seconds, bootstrap likelihood -14362.278690, best rearrangement setting 15
Bootstrap[4]: Time 0.978579 seconds, bootstrap likelihood -13990.464064, best rearrangement setting 10
Bootstrap[5]: Time 0.977690 seconds, bootstrap likelihood -13613.783502, best rearrangement setting 10
Bootstrap[6]: Time 1.020360 seconds, bootstrap likelihood -13651.994983, best rearrangement setting 6
Bootstrap[7]: Time 1.046193 seconds, bootstrap likelihood -13500.044540, best rearrangement setting 14
Bootstrap[8]: Time 0.955175 seconds, bootstrap likelihood -13904.708285, best rearrangement setting 5
Bootstrap[9]: Time 0.998075 seconds, bootstrap likelihood -13451.062222, best rearrangement setting 7
Bootstrap[10]: Time 1.011243 seconds, bootstrap likelihood -13472.421848, best rearrangement setting 7
Bootstrap[11]: Time 1.011930 seconds, bootstrap likelihood -13867.514655, best rearrangement setting 5
Bootstrap[12]: Time 1.037761 seconds, bootstrap likelihood -14012.336482, best rearrangement setting 8
Bootstrap[13]: Time 1.106701 seconds, bootstrap likelihood -13770.493315, best rearrangement setting 7
Bootstrap[14]: Time 0.991831 seconds, bootstrap likelihood -14022.355316, best rearrangement setting 12
Bootstrap[15]: Time 0.423655 seconds, bootstrap likelihood -13623.424076, best rearrangement setting 15
Bootstrap[16]: Time 1.077338 seconds, bootstrap likelihood -13321.473818, best rearrangement setting 12
Bootstrap[17]: Time 1.016488 seconds, bootstrap likelihood -13807.754066, best rearrangement setting 12
Bootstrap[18]: Time 0.978337 seconds, bootstrap likelihood -13583.556968, best rearrangement setting 5
Bootstrap[19]: Time 0.427814 seconds, bootstrap likelihood -13383.673373, best rearrangement setting 8
Bootstrap[20]: Time 1.032511 seconds, bootstrap likelihood -13704.571152, best rearrangement setting 10
Bootstrap[21]: Time 0.982269 seconds, bootstrap likelihood -13727.101238, best rearrangement setting 6
Bootstrap[22]: Time 0.983339 seconds, bootstrap likelihood -13565.099556, best rearrangement setting 5
Bootstrap[23]: Time 0.951201 seconds, bootstrap likelihood -13094.026139, best rearrangement setting 7
Bootstrap[24]: Time 1.038314 seconds, bootstrap likelihood -13337.648584, best rearrangement setting 8
Bootstrap[25]: Time 1.056842 seconds, bootstrap likelihood -13483.844071, best rearrangement setting 6
Bootstrap[26]: Time 1.005430 seconds, bootstrap likelihood -13159.624881, best rearrangement setting 12
Bootstrap[27]: Time 0.923973 seconds, bootstrap likelihood -13045.843421, best rearrangement setting 10
Bootstrap[28]: Time 1.019312 seconds, bootstrap likelihood -13276.994150, best rearrangement setting 11
Bootstrap[29]: Time 1.079153 seconds, bootstrap likelihood -13804.410809, best rearrangement setting 12
Bootstrap[30]: Time 1.054455 seconds, bootstrap likelihood -13724.169670, best rearrangement setting 15
Bootstrap[31]: Time 1.052492 seconds, bootstrap likelihood -13800.671941, best rearrangement setting 15
Bootstrap[32]: Time 1.069161 seconds, bootstrap likelihood -13125.423632, best rearrangement setting 6
Bootstrap[33]: Time 1.028776 seconds, bootstrap likelihood -13635.602138, best rearrangement setting 15
Bootstrap[34]: Time 1.053460 seconds, bootstrap likelihood -13962.923799, best rearrangement setting 11
Bootstrap[35]: Time 1.133891 seconds, bootstrap likelihood -14603.785698, best rearrangement setting 8
Bootstrap[36]: Time 1.067472 seconds, bootstrap likelihood -13717.974178, best rearrangement setting 9
Bootstrap[37]: Time 1.039769 seconds, bootstrap likelihood -14551.715056, best rearrangement setting 11
Bootstrap[38]: Time 1.008608 seconds, bootstrap likelihood -13865.819386, best rearrangement setting 8
Bootstrap[39]: Time 1.030659 seconds, bootstrap likelihood -13703.699038, best rearrangement setting 13
Bootstrap[40]: Time 1.047686 seconds, bootstrap likelihood -14058.068471, best rearrangement setting 13
Bootstrap[41]: Time 1.000824 seconds, bootstrap likelihood -14197.123657, best rearrangement setting 10
Bootstrap[42]: Time 0.928676 seconds, bootstrap likelihood -13619.338575, best rearrangement setting 5
Bootstrap[43]: Time 0.453628 seconds, bootstrap likelihood -13573.666926, best rearrangement setting 14
Bootstrap[44]: Time 1.017106 seconds, bootstrap likelihood -13786.182699, best rearrangement setting 10
Bootstrap[45]: Time 1.017306 seconds, bootstrap likelihood -13714.060983, best rearrangement setting 15
Bootstrap[46]: Time 1.019325 seconds, bootstrap likelihood -13935.244197, best rearrangement setting 14
Bootstrap[47]: Time 1.006545 seconds, bootstrap likelihood -13453.036342, best rearrangement setting 8
Bootstrap[48]: Time 1.010683 seconds, bootstrap likelihood -13639.612852, best rearrangement setting 6
Bootstrap[49]: Time 0.961369 seconds, bootstrap likelihood -13632.640379, best rearrangement setting 7
Bootstrap[50]: Time 0.999598 seconds, bootstrap likelihood -13023.532461, best rearrangement setting 7
Bootstrap[51]: Time 1.016899 seconds, bootstrap likelihood -13880.107187, best rearrangement setting 11
Bootstrap[52]: Time 1.011325 seconds, bootstrap likelihood -13384.994806, best rearrangement setting 12
Bootstrap[53]: Time 0.477697 seconds, bootstrap likelihood -13633.852578, best rearrangement setting 8
Bootstrap[54]: Time 0.429617 seconds, bootstrap likelihood -13655.580744, best rearrangement setting 9
Bootstrap[55]: Time 1.028503 seconds, bootstrap likelihood -14022.607576, best rearrangement setting 11
Bootstrap[56]: Time 1.004748 seconds, bootstrap likelihood -13721.662561, best rearrangement setting 5
Bootstrap[57]: Time 1.029707 seconds, bootstrap likelihood -13678.207950, best rearrangement setting 7
Bootstrap[58]: Time 0.982460 seconds, bootstrap likelihood -13494.841154, best rearrangement setting 10
Bootstrap[59]: Time 0.998128 seconds, bootstrap likelihood -13550.300113, best rearrangement setting 9
Bootstrap[60]: Time 1.060577 seconds, bootstrap likelihood -13867.829498, best rearrangement setting 7
Bootstrap[61]: Time 1.103038 seconds, bootstrap likelihood -14117.574392, best rearrangement setting 5
Bootstrap[62]: Time 0.970096 seconds, bootstrap likelihood -13667.237374, best rearrangement setting 11
Bootstrap[63]: Time 0.970462 seconds, bootstrap likelihood -13824.903493, best rearrangement setting 12
Bootstrap[64]: Time 0.982670 seconds, bootstrap likelihood -13416.165302, best rearrangement setting 7
Bootstrap[65]: Time 0.999217 seconds, bootstrap likelihood -13965.465649, best rearrangement setting 5
Bootstrap[66]: Time 0.935032 seconds, bootstrap likelihood -14172.316640, best rearrangement setting 5
Bootstrap[67]: Time 1.009726 seconds, bootstrap likelihood -13467.921064, best rearrangement setting 15
Bootstrap[68]: Time 1.010085 seconds, bootstrap likelihood -13913.954933, best rearrangement setting 11
Bootstrap[69]: Time 1.149558 seconds, bootstrap likelihood -13564.984927, best rearrangement setting 5
Bootstrap[70]: Time 1.052235 seconds, bootstrap likelihood -13369.800860, best rearrangement setting 8
Bootstrap[71]: Time 1.039680 seconds, bootstrap likelihood -13456.770365, best rearrangement setting 10
Bootstrap[72]: Time 1.017992 seconds, bootstrap likelihood -13849.658270, best rearrangement setting 11
Bootstrap[73]: Time 0.984324 seconds, bootstrap likelihood -13377.003657, best rearrangement setting 9
Bootstrap[74]: Time 0.493823 seconds, bootstrap likelihood -13539.018488, best rearrangement setting 5
Bootstrap[75]: Time 0.936630 seconds, bootstrap likelihood -13680.000046, best rearrangement setting 8
Bootstrap[76]: Time 1.019818 seconds, bootstrap likelihood -13474.692665, best rearrangement setting 9
Bootstrap[77]: Time 0.952795 seconds, bootstrap likelihood -13538.954515, best rearrangement setting 11
Bootstrap[78]: Time 0.985334 seconds, bootstrap likelihood -13304.851319, best rearrangement setting 15
Bootstrap[79]: Time 1.051024 seconds, bootstrap likelihood -13807.272914, best rearrangement setting 9
Bootstrap[80]: Time 1.048224 seconds, bootstrap likelihood -13202.534663, best rearrangement setting 15
Bootstrap[81]: Time 1.006623 seconds, bootstrap likelihood -13952.887034, best rearrangement setting 7
Bootstrap[82]: Time 0.960986 seconds, bootstrap likelihood -13639.282183, best rearrangement setting 6
Bootstrap[83]: Time 0.999103 seconds, bootstrap likelihood -13778.468298, best rearrangement setting 10
Bootstrap[84]: Time 0.974398 seconds, bootstrap likelihood -13572.487925, best rearrangement setting 11
Bootstrap[85]: Time 1.042921 seconds, bootstrap likelihood -14285.399598, best rearrangement setting 8
Bootstrap[86]: Time 0.937995 seconds, bootstrap likelihood -13580.898611, best rearrangement setting 7
Bootstrap[87]: Time 0.477266 seconds, bootstrap likelihood -13951.535110, best rearrangement setting 7
Bootstrap[88]: Time 0.988275 seconds, bootstrap likelihood -13490.421495, best rearrangement setting 12
Bootstrap[89]: Time 1.058670 seconds, bootstrap likelihood -13534.408189, best rearrangement setting 10
Bootstrap[90]: Time 1.130640 seconds, bootstrap likelihood -13729.421156, best rearrangement setting 8
Bootstrap[91]: Time 1.032034 seconds, bootstrap likelihood -13294.056385, best rearrangement setting 12
Bootstrap[92]: Time 1.083224 seconds, bootstrap likelihood -14055.180414, best rearrangement setting 13
Bootstrap[93]: Time 0.980218 seconds, bootstrap likelihood -13554.963381, best rearrangement setting 15
Bootstrap[94]: Time 0.979884 seconds, bootstrap likelihood -13693.769485, best rearrangement setting 5
Bootstrap[95]: Time 1.000161 seconds, bootstrap likelihood -13664.325937, best rearrangement setting 5
Bootstrap[96]: Time 1.109990 seconds, bootstrap likelihood -14162.597209, best rearrangement setting 13
Bootstrap[97]: Time 0.990710 seconds, bootstrap likelihood -14379.857148, best rearrangement setting 11
Bootstrap[98]: Time 0.934861 seconds, bootstrap likelihood -13136.620625, best rearrangement setting 6
Bootstrap[99]: Time 1.050487 seconds, bootstrap likelihood -14086.598203, best rearrangement setting 14
Bootstrap[100]: Time 1.069508 seconds, bootstrap likelihood -13630.879134, best rearrangement setting 12
Bootstrap[101]: Time 1.016772 seconds, bootstrap likelihood -13476.761794, best rearrangement setting 10
Bootstrap[102]: Time 1.080848 seconds, bootstrap likelihood -13415.773961, best rearrangement setting 8
Bootstrap[103]: Time 1.029579 seconds, bootstrap likelihood -13048.713827, best rearrangement setting 8
Bootstrap[104]: Time 1.062258 seconds, bootstrap likelihood -13450.410573, best rearrangement setting 15
Bootstrap[105]: Time 1.039081 seconds, bootstrap likelihood -13595.287754, best rearrangement setting 7
Bootstrap[106]: Time 1.049008 seconds, bootstrap likelihood -13423.285696, best rearrangement setting 6
Bootstrap[107]: Time 1.097362 seconds, bootstrap likelihood -13224.657281, best rearrangement setting 13
Bootstrap[108]: Time 0.990928 seconds, bootstrap likelihood -13819.276295, best rearrangement setting 14
Bootstrap[109]: Time 0.946575 seconds, bootstrap likelihood -13173.282209, best rearrangement setting 12
Bootstrap[110]: Time 1.066393 seconds, bootstrap likelihood -13710.562286, best rearrangement setting 7
Bootstrap[111]: Time 1.004928 seconds, bootstrap likelihood -13692.524302, best rearrangement setting 15
Bootstrap[112]: Time 1.025323 seconds, bootstrap likelihood -13101.814917, best rearrangement setting 14
Bootstrap[113]: Time 0.974978 seconds, bootstrap likelihood -13346.162994, best rearrangement setting 5
Bootstrap[114]: Time 1.019910 seconds, bootstrap likelihood -14366.246406, best rearrangement setting 6
Bootstrap[115]: Time 1.033964 seconds, bootstrap likelihood -13551.456476, best rearrangement setting 7
Bootstrap[116]: Time 1.010331 seconds, bootstrap likelihood -13342.795694, best rearrangement setting 11
Bootstrap[117]: Time 0.983810 seconds, bootstrap likelihood -13382.001440, best rearrangement setting 8
Bootstrap[118]: Time 1.047041 seconds, bootstrap likelihood -14068.219242, best rearrangement setting 9
Bootstrap[119]: Time 0.971809 seconds, bootstrap likelihood -13848.646260, best rearrangement setting 14
Bootstrap[120]: Time 1.028544 seconds, bootstrap likelihood -13695.952615, best rearrangement setting 12
Bootstrap[121]: Time 1.075146 seconds, bootstrap likelihood -13787.150739, best rearrangement setting 8
Bootstrap[122]: Time 1.201864 seconds, bootstrap likelihood -13717.872074, best rearrangement setting 9
Bootstrap[123]: Time 1.011135 seconds, bootstrap likelihood -13989.596625, best rearrangement setting 6
Bootstrap[124]: Time 1.060462 seconds, bootstrap likelihood -13653.021734, best rearrangement setting 11
Bootstrap[125]: Time 1.062034 seconds, bootstrap likelihood -13903.780698, best rearrangement setting 11
Bootstrap[126]: Time 0.958626 seconds, bootstrap likelihood -13829.651605, best rearrangement setting 12
Bootstrap[127]: Time 1.042347 seconds, bootstrap likelihood -14015.874980, best rearrangement setting 9
Bootstrap[128]: Time 1.023220 seconds, bootstrap likelihood -13839.831743, best rearrangement setting 11
Bootstrap[129]: Time 1.011287 seconds, bootstrap likelihood -13849.684668, best rearrangement setting 5
Bootstrap[130]: Time 1.037790 seconds, bootstrap likelihood -13773.640192, best rearrangement setting 10
Bootstrap[131]: Time 1.019837 seconds, bootstrap likelihood -13344.011974, best rearrangement setting 9
Bootstrap[132]: Time 1.107459 seconds, bootstrap likelihood -13750.068002, best rearrangement setting 14
Bootstrap[133]: Time 0.445734 seconds, bootstrap likelihood -13791.781555, best rearrangement setting 13
Bootstrap[134]: Time 1.053070 seconds, bootstrap likelihood -13753.466388, best rearrangement setting 6
Bootstrap[135]: Time 1.049412 seconds, bootstrap likelihood -13267.572893, best rearrangement setting 11
Bootstrap[136]: Time 0.442156 seconds, bootstrap likelihood -13312.741706, best rearrangement setting 13
Bootstrap[137]: Time 0.984825 seconds, bootstrap likelihood -13217.091874, best rearrangement setting 6
Bootstrap[138]: Time 0.987339 seconds, bootstrap likelihood -13604.306825, best rearrangement setting 15
Bootstrap[139]: Time 1.020594 seconds, bootstrap likelihood -13631.231591, best rearrangement setting 5
Bootstrap[140]: Time 1.111723 seconds, bootstrap likelihood -13632.229578, best rearrangement setting 13
Bootstrap[141]: Time 1.065916 seconds, bootstrap likelihood -14068.839495, best rearrangement setting 5
Bootstrap[142]: Time 0.982707 seconds, bootstrap likelihood -13491.749984, best rearrangement setting 15
Bootstrap[143]: Time 1.021516 seconds, bootstrap likelihood -14097.199160, best rearrangement setting 7
Bootstrap[144]: Time 0.466091 seconds, bootstrap likelihood -13602.913756, best rearrangement setting 13
Bootstrap[145]: Time 1.052069 seconds, bootstrap likelihood -13845.132633, best rearrangement setting 7
Bootstrap[146]: Time 1.104505 seconds, bootstrap likelihood -13802.728551, best rearrangement setting 9
Bootstrap[147]: Time 1.010983 seconds, bootstrap likelihood -13878.626443, best rearrangement setting 12
Bootstrap[148]: Time 0.973347 seconds, bootstrap likelihood -13269.750125, best rearrangement setting 8
Bootstrap[149]: Time 1.058752 seconds, bootstrap likelihood -13189.308012, best rearrangement setting 12
Bootstrap[150]: Time 1.103543 seconds, bootstrap likelihood -13970.257391, best rearrangement setting 14
Bootstrap[151]: Time 1.036328 seconds, bootstrap likelihood -13716.968241, best rearrangement setting 5
Bootstrap[152]: Time 0.406164 seconds, bootstrap likelihood -13825.274879, best rearrangement setting 5
Bootstrap[153]: Time 1.010169 seconds, bootstrap likelihood -13743.002806, best rearrangement setting 13
Bootstrap[154]: Time 1.065407 seconds, bootstrap likelihood -13888.008605, best rearrangement setting 14
Bootstrap[155]: Time 0.939031 seconds, bootstrap likelihood -13301.959460, best rearrangement setting 13
Bootstrap[156]: Time 1.047735 seconds, bootstrap likelihood -13482.012779, best rearrangement setting 11
Bootstrap[157]: Time 1.056684 seconds, bootstrap likelihood -13386.465080, best rearrangement setting 8
Bootstrap[158]: Time 1.043898 seconds, bootstrap likelihood -14300.904601, best rearrangement setting 8
Bootstrap[159]: Time 0.982824 seconds, bootstrap likelihood -13582.252442, best rearrangement setting 5
Bootstrap[160]: Time 1.114556 seconds, bootstrap likelihood -14232.779353, best rearrangement setting 15
Bootstrap[161]: Time 1.036926 seconds, bootstrap likelihood -13626.299717, best rearrangement setting 13
Bootstrap[162]: Time 1.009614 seconds, bootstrap likelihood -13922.856961, best rearrangement setting 13
Bootstrap[163]: Time 1.045780 seconds, bootstrap likelihood -14084.975270, best rearrangement setting 12
Bootstrap[164]: Time 1.042339 seconds, bootstrap likelihood -13593.111431, best rearrangement setting 7
Bootstrap[165]: Time 1.017671 seconds, bootstrap likelihood -14070.181492, best rearrangement setting 13
Bootstrap[166]: Time 1.073937 seconds, bootstrap likelihood -14242.225707, best rearrangement setting 10
Bootstrap[167]: Time 0.990916 seconds, bootstrap likelihood -12885.058262, best rearrangement setting 12
Bootstrap[168]: Time 0.979691 seconds, bootstrap likelihood -13911.880070, best rearrangement setting 14
Bootstrap[169]: Time 1.019420 seconds, bootstrap likelihood -14351.782630, best rearrangement setting 10
Bootstrap[170]: Time 0.995457 seconds, bootstrap likelihood -13581.034922, best rearrangement setting 5
Bootstrap[171]: Time 1.069024 seconds, bootstrap likelihood -14039.136088, best rearrangement setting 11
Bootstrap[172]: Time 1.045801 seconds, bootstrap likelihood -13925.962871, best rearrangement setting 12
Bootstrap[173]: Time 1.072751 seconds, bootstrap likelihood -13349.564256, best rearrangement setting 11
Bootstrap[174]: Time 1.022329 seconds, bootstrap likelihood -13497.805080, best rearrangement setting 15
Bootstrap[175]: Time 0.970757 seconds, bootstrap likelihood -13581.527476, best rearrangement setting 14
Bootstrap[176]: Time 0.941052 seconds, bootstrap likelihood -13513.465702, best rearrangement setting 8
Bootstrap[177]: Time 0.974264 seconds, bootstrap likelihood -13885.489368, best rearrangement setting 8
Bootstrap[178]: Time 1.008002 seconds, bootstrap likelihood -13761.000457, best rearrangement setting 14
Bootstrap[179]: Time 1.027831 seconds, bootstrap likelihood -13818.355724, best rearrangement setting 5
Bootstrap[180]: Time 1.055856 seconds, bootstrap likelihood -13240.487159, best rearrangement setting 12
Bootstrap[181]: Time 1.048152 seconds, bootstrap likelihood -13302.070244, best rearrangement setting 14
Bootstrap[182]: Time 0.432957 seconds, bootstrap likelihood -13282.704949, best rearrangement setting 7
Bootstrap[183]: Time 1.026252 seconds, bootstrap likelihood -13728.641597, best rearrangement setting 11
Bootstrap[184]: Time 0.991074 seconds, bootstrap likelihood -14146.070730, best rearrangement setting 15
Bootstrap[185]: Time 0.951120 seconds, bootstrap likelihood -13329.439646, best rearrangement setting 8
Bootstrap[186]: Time 1.035351 seconds, bootstrap likelihood -13444.617216, best rearrangement setting 13
Bootstrap[187]: Time 0.988260 seconds, bootstrap likelihood -13405.964605, best rearrangement setting 8
Bootstrap[188]: Time 1.025584 seconds, bootstrap likelihood -13491.376238, best rearrangement setting 12
Bootstrap[189]: Time 1.048237 seconds, bootstrap likelihood -13775.372710, best rearrangement setting 11
Bootstrap[190]: Time 0.996929 seconds, bootstrap likelihood -13693.506991, best rearrangement setting 15
Bootstrap[191]: Time 1.094041 seconds, bootstrap likelihood -13371.573808, best rearrangement setting 8
Bootstrap[192]: Time 1.137359 seconds, bootstrap likelihood -13825.789222, best rearrangement setting 8
Bootstrap[193]: Time 1.089415 seconds, bootstrap likelihood -14647.926967, best rearrangement setting 10
Bootstrap[194]: Time 1.041020 seconds, bootstrap likelihood -13614.803474, best rearrangement setting 8
Bootstrap[195]: Time 0.977150 seconds, bootstrap likelihood -13740.530136, best rearrangement setting 7
Bootstrap[196]: Time 1.048117 seconds, bootstrap likelihood -13702.880106, best rearrangement setting 11
Bootstrap[197]: Time 0.941431 seconds, bootstrap likelihood -14000.589079, best rearrangement setting 8
Bootstrap[198]: Time 1.064273 seconds, bootstrap likelihood -13756.352450, best rearrangement setting 15
Bootstrap[199]: Time 1.009033 seconds, bootstrap likelihood -14321.778016, best rearrangement setting 8


Stopped Rapid BS search after 200 replicates with MRE-based Bootstopping criterion
WRF Average of 100 random splits: 1.174211
Overall Time for 200 Rapid Bootstraps 198.558148 seconds
Average Time per Rapid Bootstrap 0.992791 seconds

Starting ML Search ...

Fast ML optimization finished

Fast ML search Time: 77.806336 seconds

Slow ML Search 0 Likelihood: -13710.024440
Slow ML Search 1 Likelihood: -13710.024440
Slow ML Search 2 Likelihood: -13710.024440
Slow ML Search 3 Likelihood: -13710.024440
Slow ML Search 4 Likelihood: -13710.024440
Slow ML Search 5 Likelihood: -13710.024440
Slow ML Search 6 Likelihood: -13710.024440
Slow ML Search 7 Likelihood: -13710.024440
Slow ML Search 8 Likelihood: -13710.024440
Slow ML Search 9 Likelihood: -13710.024440
Slow ML optimization finished

Slow ML search Time: 27.400497 seconds
Thorough ML search Time: 3.906476 seconds

Final ML Optimization Likelihood: -13710.024895

Model Information:

Model Parameters of Partition 0, Name: No Name Provided, Type of Data: DNA
alpha: 0.489260
Tree-Length: 4.523604
rate A <-> C: 0.305360
rate A <-> G: 0.602225
rate A <-> T: 0.409343
rate C <-> G: 0.506560
rate C <-> T: 1.842370
rate G <-> T: 1.000000

freq pi(A): 0.245421
freq pi(C): 0.231539
freq pi(G): 0.321051
freq pi(T): 0.201989


ML search took 109.147019 secs or 0.030319 hours

Combined Bootstrap and ML search took 307.707754 secs or 0.085474 hours

Drawing Bootstrap Support Values on best-scoring ML tree ...



Found 1 tree in File /N/dc2/projects/Lennon_Sequences/LTDE_Tree/June2017/RAxML_bestTree.LTDE.ML



Found 1 tree in File /N/dc2/projects/Lennon_Sequences/LTDE_Tree/June2017/RAxML_bestTree.LTDE.ML

Program execution info written to /N/dc2/projects/Lennon_Sequences/LTDE_Tree/June2017/RAxML_info.LTDE.ML
All 200 bootstrapped trees written to: /N/dc2/projects/Lennon_Sequences/LTDE_Tree/June2017/RAxML_bootstrap.LTDE.ML

Best-scoring ML tree written to: /N/dc2/projects/Lennon_Sequences/LTDE_Tree/June2017/RAxML_bestTree.LTDE.ML

Best-scoring ML tree with support values written to: /N/dc2/projects/Lennon_Sequences/LTDE_Tree/June2017/RAxML_bipartitions.LTDE.ML

Best-scoring ML tree with support values as branch labels written to: /N/dc2/projects/Lennon_Sequences/LTDE_Tree/June2017/RAxML_bipartitionsBranchLabels.LTDE.ML

Overall execution time for full ML analysis: 307.733616 secs or 0.085482 hours or 0.003562 days

